# Generated by Django 2.0 on 2023-04-13 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('salary', models.CharField(max_length=20, verbose_name='Salary')),
                ('bonus', models.TextField(max_length=50, verbose_name='Bonus')),
                ('mulct', models.CharField(max_length=50, verbose_name='Mulct')),
                ('total', models.CharField(max_length=50, verbose_name='Total')),
                ('pay_day', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Pay Day')),
            ],
            options={
                'permissions': (('view_payrollmodel', 'Can view payroll model'),),
            },
        ),
    ]
