# Generated by Django 2.0 on 2023-03-20 06:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Your name')),
                ('age', models.IntegerField(verbose_name='Your age')),
                ('birthday', models.DateField(default=datetime.datetime(2023, 3, 20, 6, 51, 12, 718285, tzinfo=utc), verbose_name='Birthday')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('email', models.EmailField(default='Example@gmail.com', max_length=254, verbose_name='Email')),
                ('gender', models.CharField(default='other', max_length=20, verbose_name='Gender')),
                ('is_married', models.BooleanField(default=False, verbose_name='Is Married')),
                ('joining_date', models.DateTimeField(default=datetime.datetime(2023, 3, 20, 6, 51, 12, 718285, tzinfo=utc), verbose_name='Joining Date')),
                ('image', models.ImageField(default=None, upload_to='', verbose_name='Image')),
            ],
        ),
    ]
