# Generated by Django 2.0 on 2023-03-30 09:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hr_tags', '0001_initial'),
        ('hr_jobs', '0003_auto_20230330_1616'),
        ('hr_employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr_jobs.JobModel'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='tags',
            field=models.ManyToManyField(to='hr_tags.EmployeeTagModel'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 3, 30, 9, 48, 53, 163358, tzinfo=utc), verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='image',
            field=models.ImageField(default=None, upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='joining_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 9, 48, 53, 163358, tzinfo=utc), verbose_name='Joining Date'),
        ),
    ]
