# Generated by Django 2.0 on 2023-03-30 09:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employees', '0002_auto_20230330_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 3, 30, 9, 55, 12, 889573, tzinfo=utc), verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='joining_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 9, 55, 12, 889573, tzinfo=utc), verbose_name='Joining Date'),
        ),
    ]
