# Generated by Django 2.0 on 2023-03-30 10:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employees', '0003_auto_20230330_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 3, 30, 10, 18, 42, 490395, tzinfo=utc), verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='joining_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 10, 18, 42, 490395, tzinfo=utc), verbose_name='Joining Date'),
        ),
    ]
