# Generated by Django 2.0 on 2023-04-03 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employees', '0005_auto_20230330_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeemodel',
            options={'permissions': (('view_employeemodel', 'Can view employee model'),)},
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 4, 3, 14, 44, 9, 85306, tzinfo=utc), verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='joining_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 14, 44, 9, 85306, tzinfo=utc), verbose_name='Joining Date'),
        ),
    ]
