# Generated by Django 2.0 on 2023-03-29 08:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
                ('meeting_date', models.DateField(default=datetime.datetime(2023, 3, 29, 8, 27, 40, 104479, tzinfo=utc), verbose_name='Meeting Date')),
                ('total_employees', models.CharField(default=None, max_length=20, verbose_name='Total Employees')),
                ('note', models.TextField(max_length=100, verbose_name='Note')),
                ('status', models.CharField(default='draft', max_length=10, verbose_name='Status')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2023, 3, 29, 8, 27, 40, 104479, tzinfo=utc), verbose_name='Create Date')),
                ('attachment', models.ImageField(blank=True, default=None, upload_to='images', verbose_name='Attachment')),
            ],
        ),
    ]
