# Generated by Django 2.0 on 2023-04-04 08:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hr_departments', '0002_auto_20230330_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentmodel',
            options={'permissions': (('view_departmentmodel', 'Can view department model'),)},
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 8, 7, 47, 908418, tzinfo=utc), verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='meeting_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 4, 8, 7, 47, 908418, tzinfo=utc), verbose_name='Meeting Date'),
        ),
    ]
