# Generated by Django 2.0 on 2023-04-04 08:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_employees', '0008_auto_20230404_1437'),
        ('hr_tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('rank', models.IntegerField(verbose_name='Rank')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='End Date')),
                ('note', models.TextField(max_length=100, verbose_name='Note')),
                ('status', models.CharField(default='draft', max_length=10, verbose_name='Status')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('attachment', models.ImageField(default=None, upload_to='images', verbose_name='Image')),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr_employees.EmployeeModel')),
                ('tags', models.ManyToManyField(to='hr_tags.ContractTagModel')),
            ],
            options={
                'permissions': (('view_contractmodel', 'Can view contract model'),),
            },
        ),
    ]
