# Generated by Django 2.0 on 2023-03-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsmodel',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
    ]
