# Generated by Django 2.0 on 2023-03-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='attachment',
            field=models.ImageField(blank=True, default=None, upload_to='images', verbose_name='Image'),
        ),
    ]
