# Generated by Django 2.0 on 2023-03-30 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_tags', '0001_initial'),
        ('hr_departments', '0002_auto_20230330_1616'),
        ('hr_jobs', '0002_auto_20230327_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr_departments.DepartmentModel'),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='tags',
            field=models.ManyToManyField(to='hr_tags.JobTagModel'),
        ),
    ]
