# Generated by Django 2.0 on 2023-04-06 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=20, verbose_name='ItemName')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.CharField(max_length=20, verbose_name='Price')),
                ('amount', models.CharField(max_length=20, verbose_name='Salary')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('category', models.CharField(default='', max_length=50, verbose_name='Category')),
                ('employee', models.CharField(max_length=50, verbose_name='Employee')),
            ],
            options={
                'permissions': (('view_payrollmodel', 'Can view payroll model'),),
            },
        ),
    ]
