# Generated by Django 2.0 on 2023-04-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensemodel',
            options={'permissions': (('view_expensemodel', 'Can view expensemodel model'),)},
        ),
    ]
